# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b2ff8316128866082d53079c93eea7ad7feef395e5f87a17901f82bd58295dc6304c8cc311b1a4fae00fb7a5b63a003fed5c3decc745b9e4f3b410dcef39c6d

test:
  secret_key_base: c84cea72f679c13c66be7aeb76ad4ee05f54bb79fa7b76ae388e83b0ddaaa40b1288e909a44c077172ba59afdf93cb3d6123841c9f9528c63cf100e86c9e1716

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
